version: 2.1

executors:
  node12:
    docker:
      - image: circleci/node:12

jobs:
  install:
    executor: node12

    working_directory: ~/repo

    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-

      - run:
          name: Install dependendies
          command: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run:
          name: Install JUnit coverage reporter
          command: yarn add --dev jest-junit
  jest:
    executor: node12

    working_directory: ~/repo

    steps:
      - run:
          name: Ensure reports directory is present
          command: mkdir -p reports/jest

      - run:
          name: Run tests with JUnit as reporter
          command: yarn test --ci --runInBand --reporters=default --reporters=jest-junit
          environment:
            JEST_JUNIT_OUTPUT_DIR: ./reports/jest
            JEST_JUNIT_OUTPUT_NAME: results.xml
            JEST_JUNIT_SUITE_NAME: "{filename}"

      - store_artifacts:
          path: ./reports/jest

      - store_test_results:
          path: ./reports
  coverage:
    executor: node12

    working_directory: ~/repo

    steps:
      - run:
          name: Run tests coverage
          command: yarn test --ci --coverage

      - store_artifacts:
          path: ./coverage

workflows:
  test:
    jobs:
      - install
      - jest:
          requires:
            - install
      - coverage:
          requires:
            - install
