version: 2
jobs:
  build:
    docker:
      - image: circleci/node:12

    working_directory: ~/repo

    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-

      - run:
          name: Install dependendies
          command: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run:
          name: Install JUnit coverage reporter
          command: yarn add --dev jest-junit

      - run:
          name: Run Tests with JUnit as reporter
          command: |
            mkdir -p ./test-results/junit
            yarn test --ci --runInBand --reporters=default --reporters=jest-junit
          environment:
            JEST_JUNIT_OUTPUT_DIR: ./reports/junit/

      - store_artifacts:
          path: ./reports/junit

      - store_test_results:
          path: ./reports/junit
